import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "Both"

opacity = 0.9
blur = true

startup_mode = "Maximized"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[shell]
program = "/bin/bash"
args = [
  "-c",
  """
  # Set PATH to include Homebrew
  export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
  
  if command -v tmux &>/dev/null; then
    if tmux has-session 2>/dev/null; then
      exec tmux attach
    else
      exec tmux new-session
    fi
  elif command -v zsh &>/dev/null; then
    exec zsh
  else
    exec $SHELL
  fi
  """
]
